apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: ctlplane
    osp/net-attach-def-type: standard
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane",
      "type": "macvlan",
      "master": "ospbr",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.122.0/24",
        "range_start": "192.168.122.30",
        "range_end": "192.168.122.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: datacentre
    osp/net-attach-def-type: standard
  name: datacentre
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "datacentre",
      "type": "bridge",
      "bridge": "ospbr",
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: internalapi
    osp/net-attach-def-type: standard
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "macvlan",
      "master": "internalapi",
      "ipam": {
        "type": "whereabouts",
        "range": "172.17.0.0/24",
        "range_start": "172.17.0.30",
        "range_end": "172.17.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: storage
    osp/net-attach-def-type: standard
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "macvlan",
      "master": "storage",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.0.0/24",
        "range_start": "172.18.0.30",
        "range_end": "172.18.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: swift
    osp/net-attach-def-type: standard
  name: swift
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "swift",
      "type": "macvlan",
      "master": "swift",
      "ipam": {
        "type": "whereabouts",
        "range": "172.22.0.0/24",
        "range_start": "172.22.0.30",
        "range_end": "172.22.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: tenant
    osp/net-attach-def-type: standard
  name: tenant
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant",
      "type": "macvlan",
      "master": "tenant",
      "ipam": {
        "type": "whereabouts",
        "range": "172.19.0.0/24",
        "range_start": "172.19.0.30",
        "range_end": "172.19.0.70"
      }
    }
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: ctlplane
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.80-192.168.122.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: internalapi
  namespace: metallb-system
spec:
  addresses:
  - 172.17.0.80-172.17.0.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: storage
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.80-172.18.0.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: swift
  namespace: metallb-system
spec:
  addresses:
  - 172.22.0.80-172.22.0.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: tenant
  namespace: metallb-system
spec:
  addresses:
  - 172.19.0.80-172.19.0.90
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ctlplane
  namespace: metallb-system
spec:
  interfaces:
  - ospbr
  ipAddressPools:
  - ctlplane
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internalapi
  namespace: metallb-system
spec:
  interfaces:
  - internalapi
  ipAddressPools:
  - internalapi
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: storage
  namespace: metallb-system
spec:
  interfaces:
  - storage
  ipAddressPools:
  - storage
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: swift
  namespace: metallb-system
spec:
  interfaces:
  - swift
  ipAddressPools:
  - swift
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tenant
  namespace: metallb-system
spec:
  interfaces:
  - tenant
  ipAddressPools:
  - tenant
---
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
  namespace: openstack
spec:
  networks:
  - dnsDomain: ctlplane.example.com
    mtu: 1500
    name: ctlplane
    subnets:
    - allocationRanges:
      - end: 192.168.122.120
        start: 192.168.122.100
      - end: 192.168.122.170
        start: 192.168.122.150
      cidr: 192.168.122.0/24
      gateway: 192.168.122.1
      name: subnet1
  - dnsDomain: internalapi.example.com
    mtu: 1496
    name: internalapi
    subnets:
    - allocationRanges:
      - end: 172.17.0.250
        start: 172.17.0.100
      cidr: 172.17.0.0/24
      name: subnet1
      vlan: 20
  - dnsDomain: external.example.com
    mtu: 1496
    name: external
    subnets:
    - allocationRanges:
      - end: 172.21.0.250
        start: 172.21.0.100
      cidr: 172.21.0.0/24
      name: subnet1
      vlan: 44
  - dnsDomain: storage.example.com
    mtu: 1496
    name: storage
    subnets:
    - allocationRanges:
      - end: 172.18.0.250
        start: 172.18.0.100
      cidr: 172.18.0.0/24
      name: subnet1
      vlan: 21
  - dnsDomain: tenant.example.com
    mtu: 1496
    name: tenant
    subnets:
    - allocationRanges:
      - end: 172.19.0.250
        start: 172.19.0.100
      cidr: 172.19.0.0/24
      name: subnet1
      vlan: 22
  - dnsDomain: swift.example.com
    mtu: 1500
    name: swift
    subnets:
    - allocationRanges:
      - end: 172.22.0.250
        start: 172.22.0.100
      cidr: 172.22.0.0/24
      name: subnet1
      vlan: 25
  - dnsDomain: storagemgmt.example.com
    mtu: 1500
    name: storagemgmt
    subnets:
    - allocationRanges:
      - end: 172.20.0.250
        start: 172.20.0.100
      cidr: 172.20.0.0/24
      name: subnet1
      vlan: 23