---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# This component inherits from ovs-dpdk-sriov and only overrides
# the NNCP component to support IPv6 networking

components:
  - ../ovs-dpdk-sriov
  - nncp
