#
# CHANGEME:
#
# - Change "data.['ceph.client.openstack.keyring']" to be the base64-encoded contents of the keyring that your
#   OpenStack deployment will use to access Ceph
# - Change "data.['ceph.conf']" to be the base64-encoded contents of your Ceph cluster's ceph.conf
#

apiVersion: v1
data:
  ceph.client.openstack.keyring: W2NsaWVudC5vcGVuc3RhY2tdCglrZXkgPSBBUUNnNGhabEZNZElDaEFBTkp1anIxNWFkTnY5bVNlTDJhY1U0UT09CgljYXBzIG1nciA9ICJhbGxvdyBydyIKCWNhcHMgbW9uID0gImFsbG93IHIiCgljYXBzIG9zZCA9ICJhbGxvdyBjbGFzcy1yZWFkIG9iamVjdF9wcmVmaXggcmJkX2NoaWxkcmVuLCBhbGxvdyByd3ggcG9vbD12bXMsIGFsbG93IHJ3eCBwb29sPXZvbHVtZXMsIGFsbG93IHJ3eCBwb29sPWltYWdlcywgYWxsb3cgcnd4IHBvb2w9Y2VwaGZzLmNlcGhmcy5tZXRhLCBhbGxvdyByd3ggcG9vbD1jZXBoZnMuY2VwaGZzLmRhdGEiCg== # CHANGEME
  ceph.conf: IyBtaW5pbWFsIGNlcGguY29uZiBmb3IgOWQzYjQ4ZTgtNWVkNC0xMWVlLTg4YzctNTI1NDAwODVhNDcxCltnbG9iYWxdCglmc2lkID0gOWQzYjQ4ZTgtNWVkNC0xMWVlLTg4YzctNTI1NDAwODVhNDcxCgltb25faG9zdCA9IFt2MjoxNzIuMTguMC4xMDA6MzMwMC8wLHYxOjE3Mi4xOC4wLjEwMDo2Nzg5LzBdIFt2MjoxNzIuMTguMC4xMDE6MzMwMC8wLHYxOjE3Mi4xOC4wLjEwMTo2Nzg5LzBdIFt2MjoxNzIuMTguMC4xMDI6MzMwMC8wLHYxOjE3Mi4xOC4wLjEwMjo2Nzg5LzBdCg== # CHANGEME
kind: Secret
metadata:
  name: ceph-conf-files
  namespace: openstack
type: Opaque
