#
# CHANGEME:
#
# - Change "data['ssh-privatekey']" to be the base64-encoded private key you would
#   use for a potential future migration
# - Change "data['ssh-publickey']" to be the base64-encoded public key you would
#   use for a potential future migration
#

apiVersion: v1
data:
  ssh-privatekey: # CHANGEME
  ssh-publickey: # CHANGEME
kind: Secret
metadata:
  name: nova-migration-ssh-key
  namespace: openstack
type: kubernetes.io/ssh-auth
