#
# Additional advertisements can be added here if needed for other networks
#

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ctlplane
  namespace: metallb-system
spec:
  ipAddressPools:
  - ctlplane
  interfaces:
  # Change this interface to the appropriate OpenStack NIC for your environment
  - enp7s0 # CHANGEME
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internalapi
  namespace: metallb-system
spec:
  ipAddressPools:
  - internalapi
  interfaces:
  # Change this interface to the appropriate OpenStack VLAN NIC for your environment
  - enp7s0.20 # CHANGEME
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: storage
  namespace: metallb-system
spec:
  ipAddressPools:
  - storage
  interfaces:
  # Change this interface to the appropriate OpenStack VLAN NIC for your environment
  - enp7s0.21 # CHANGEME
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tenant
  namespace: metallb-system
spec:
  ipAddressPools:
  - tenant
  interfaces:
  # Change this interface to the appropriate OpenStack VLAN NIC for your environment
  - enp7s0.22 # CHANGEME
