---
# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-nodeset-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  ssh_keys:
    authorized: CHANGEME
    private: CHANGEME2
    public: CHANGEME3

  # Do not remove the nova key. It allows us to reuse dataplane component.
  nova:
    migration:
      ssh_keys:
        private: PLACEHOLDER
        public: PLACEHOLDER

  nodeset:
    ansible:
      ansibleUser: cloud-admin
      ansiblePort: 22
      ansibleVars:
        timesync_ntp_servers:
          - hostname: clock.redhat.com

        gather_facts: false
        enable_debug: false

        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false

        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges:
          - '192.168.122.0/24'

        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
            - type: interface
              name: nic1
              mtu: {{ external_mtu }}
              dns_servers: {{ ctlplane_dns_nameservers }}
              domain: {{ dns_search_domains }}
              use_dhcp: false
              addresses:
                - ip_netmask: {{ external_ip }}/{{ external_cidr }}
              routes: {{ external_host_routes }}
            - type: ovs_bridge
              name: osp_trunk
              mtu: {{ min_viable_mtu }}
              use_dhcp: false
              dns_servers: {{ ctlplane_dns_nameservers }}
              domain: {{ dns_search_domains }}
              addresses:
                - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
              routes: {{ ctlplane_host_routes }}
              members:
                - type: interface
                  name: nic2
                  mtu: {{ min_viable_mtu }}
                  # force the MAC address of the bridge to this interface
                  primary: true
          {% for network in nodeset_networks %}
          {% if network != 'external' %}
                - type: vlan
                  mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                  vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
                  addresses:
                    - ip_netmask: >-
                        {{
                          lookup('vars', networks_lower[network] ~ '_ip')
                        }}/{{
                          lookup('vars', networks_lower[network] ~ '_cidr')
                        }}
                  routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
          {% endif %}
          {% endfor %}

        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth1

        edpm_ceph_hci_pre_enabled_services:
          - ceph_mon
          - ceph_mgr
          - ceph_osd
          - ceph_rgw
          - ceph_nfs
          - ceph_rgw_frontend
          - ceph_nfs_frontend

        storage_mtu: 1500
        storage_mgmt_mtu: 1500
        storage_mgmt_vlan_id: 123
        storage_mgmt_cidr: "24"
        storage_mgmt_host_routes: []

        external_mtu: 1500
        external_cidr: "26"
        external_host_routes:
          - ip_netmask: 10.42.66.128/26
            next_hop: 10.42.66.189

    networks:
      - defaultRoute: true
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: storagemgmt
        subnetName: subnet1
      - name: external
        subnetName: subnet1

    nodes:
      edpm-ceph-0:
        hostName: edpm-ceph-0
        ansible:
          ansibleHost: 192.168.122.106
        networks:
          - name: ctlplane
            subnetName: subnet1
            defaultRoute: true
            fixedIP: 192.168.122.106
          - name: internalapi
            subnetName: subnet1
          - name: storage
            subnetName: subnet1
          - name: storagemgmt
            subnetName: subnet1
          - name: external
            subnetName: subnet1
            fixedIP: 10.46.22.135
      edpm-ceph-1:
        hostName: edpm-ceph-1
        ansible:
          ansibleHost: 192.168.122.107
        networks:
          - name: ctlplane
            subnetName: subnet1
            defaultRoute: true
            fixedIP: 192.168.122.107
          - name: internalapi
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1
          - name: storagemgmt
            subnetName: subnet1
          - name: external
            subnetName: subnet1
            fixedIP: 10.46.22.136
      edpm-ceph-2:
        hostName: edpm-networker-2
        ansible:
          ansibleHost: 192.168.122.108
        networks:
          - name: ctlplane
            subnetName: subnet1
            defaultRoute: true
            fixedIP: 192.168.122.108
          - name: internalapi
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1
          - name: storagemgt
            subnetName: subnet1
          - name: external
            subnetName: subnet1
            fixedIP: 10.46.22.137

    services:
      - bootstrap
      - configure-network
      - validate-network
      - install-os
      - ceph-hci-pre
      - configure-os
      - ssh-known-hosts
      - run-os
      - reboot-os
      - install-certs
