#
# CHANGEME:
#
# - Change "spec.networks[*].dnsDomain" to use something more specific if desired
# - Change "spec.networks[*].subnets[0].(allocationRanges|cidr|gateway)" to use different IPs if needed
#

apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
  namespace: openstack
spec:
  networks:
    - dnsDomain: ctlplane.example.com
      name: CtlPlane
      subnets:
        - allocationRanges:
            - end: 192.168.122.120 # CHANGEME
              start: 192.168.122.100 # CHANGEME
            - end: 192.168.122.200 # CHANGEME
              start: 192.168.122.150 # CHANGEME
          cidr: 192.168.122.0/24 # CHANGEME
          gateway: 192.168.122.1 # CHANGEME
          name: subnet1
    - dnsDomain: internalapi.example.com
      name: InternalApi
      subnets:
        - allocationRanges:
            - end: 172.17.0.250
              start: 172.17.0.100
          cidr: 172.17.0.0/24
          name: subnet1
          vlan: 20
    - dnsDomain: external.example.com
      name: External
      subnets:
        - allocationRanges:
            - end: 10.0.0.250
              start: 10.0.0.100
          cidr: 10.0.0.0/24
          gateway: 10.0.0.1
          name: subnet1
    - dnsDomain: storage.example.com
      name: Storage
      subnets:
        - allocationRanges:
            - end: 172.18.0.250
              start: 172.18.0.100
          cidr: 172.18.0.0/24
          name: subnet1
          vlan: 21
      mtu: 9000
    - dnsDomain: storagemgmt.example.com
      name: StorageMgmt
      subnets:
        - allocationRanges:
            - end: 172.20.0.250
              start: 172.20.0.100
          cidr: 172.20.0.0/24
          name: subnet1
          vlan: 23
      mtu: 9000
    - dnsDomain: tenant.example.com
      name: Tenant
      subnets:
        - allocationRanges:
            - end: 172.19.0.250
              start: 172.19.0.100
          cidr: 172.19.0.0/24
          name: subnet1
          vlan: 22
