---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../../../lib/dataplane/networker-nodeset

resources:
  - baremetalset-password-secret.yaml

replacements:
  - source:
      kind: ConfigMap
      name: networker-nodeset-values
      fieldPath: data.root_password
    targets:
      - select:
          kind: Secret
          name: baremetalset-password-secret
        fieldPaths:
          - data.NodeRootPassword
        options:
          create: true

  - source:
      kind: ConfigMap
      name: networker-nodeset-values
      fieldPath: data.baremetalSetTemplate
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-networker
        fieldPaths:
          - spec.baremetalSetTemplate
        options:
          create: true
