---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - nova-ceph.yaml

replacements:
  # Nodeset services override for Ceph
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-ceph
      fieldPath: data.nodeset.services
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.services
        options:
          create: true
  # Nova Ceph configuration
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-ceph
      fieldPath: data.nova.ceph.conf
    targets:
      - select:
          kind: ConfigMap
          name: ceph-nova
        fieldPaths:
          - data.03-ceph-nova\.conf
        options:
          create: true
  # EDPM nodeset extraMounts
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-ceph
      fieldPath: data.extraMounts
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.nodeTemplate.extraMounts
        options:
          create: true
