---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../dt/uni05epsilon/edpm-pre-ceph/deployment

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneDeployment
      name: edpm-deployment-pre-ceph
    patch: |
      - op: add
        path: /spec/nodeSets/-
        value: openstack-edpm-2

replacements:
  - source:
      kind: ConfigMap
      name: edpm-deployment-values
      fieldPath: data.servicesOverride
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.servicesOverride
        options:
          create: true
