---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

components:
  - ../../../../../lib/dataplane/deployment

replacements:
  - source:
      kind: ConfigMap
      name: edpm-nodeset-post-driver-values
      fieldPath: data.servicesOverride
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.servicesOverride
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-post-driver-values
      fieldPath: data.ansibleExtraVars
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.ansibleExtraVars
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-post-driver-values
      fieldPath: data.deployment.name
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - metadata.name
        options:
          create: true
