apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
# Set namespace to OpenStack on all namespaced objects without a namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openstack
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true

components:
- ../bases/networking
- ../bases/osp-control-plane

resources:
- netattach_ctlplane.yaml
- netattach_internalapi.yaml
- netattach_storage.yaml
- netattach_tenant.yaml
- ../bases/storage
