# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  node_0:
    name: dell-r640-046
    internalapi_ip: 172.17.0.5
    tenant_ip: 172.19.0.5
    ctlplane_ip: 192.168.122.10
    storage_ip: 172.18.0.5
  node_1:
    name: dell-r640-047
    internalapi_ip: 172.17.0.6
    tenant_ip: 172.19.0.6
    ctlplane_ip: 192.168.122.11
    storage_ip: 172.18.0.6
  node_2:
    name: dell-r640-048
    internalapi_ip: 172.17.0.7
    tenant_ip: 172.19.0.7
    ctlplane_ip: 192.168.122.12
    storage_ip: 172.18.0.7

  internalapi:
    iface: ens1f0
    vlan: 120
    lb_addresses:
    - 172.17.0.80-172.17.0.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/allow-shared-ip: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.80
  storage:
    iface: ens1f1
    vlan: 130
    lb_addresses:
    - 172.18.0.80-172.18.0.90
  tenant:
    iface: ens1f0
    vlan: 121
    lb_addresses:
    - 172.19.0.80-172.19.0.90
  ctlplane:
    iface: ens1f0
    vlan: 122
    lb_addresses:
    - 192.168.122.80-192.168.122.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: ctlplane
      metallb.universe.tf/allow-shared-ip: ctlplane
      metallb.universe.tf/loadBalancerIPs: 192.168.122.80

  rabbitmq:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.85
  rabbitmq-cell1:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.86

  lbServiceType: LoadBalancer
  storageClass: local
