---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../lib/dataplane/deployment

patches:
  - target:
      kind: OpenStackDataPlaneDeployment
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: ceph-deploy

      - op: replace
        path: /spec/nodeSets
        value:
          - ceph-nodes
