---
vas:
  hci:
    stages:
      - path: examples/va/hci/control-plane/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=5m
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/hci/control-plane
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=60m
        values:
          - name: service-values
            src_file: service-values.yaml
          - name: network-values
            src_file: nncp/values.yaml
        build_output: ../control-plane.yaml

      - path: examples/va/hci/edpm-pre-ceph/nodeset
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=10m
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: nodeset-pre-ceph.yaml

      - path: examples/va/hci/edpm-pre-ceph/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=30m
        values:
          - name: edpm-deployment-values
            src_file: values.yaml
        build_output: deployment-pre-ceph.yaml
        post_stage_run:
          - name: Deploy Ceph
            type: playbook
            source: "../../playbooks/ceph.yml"
            inventory: "${HOME}/ci-framework-data/artifacts/zuul_inventory.yml"

      - path: examples/va/hci
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=10m
        values:
          - name: service-values
            src_file: service-values.yaml
          - name: edpm-nodeset-values-post-ceph
            src_file: values.yaml
        build_output: nodeset-post-ceph.yaml

      - path: examples/va/hci/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=40m
        values:
          - name: edpm-deployment-values-post-ceph
            src_file: values.yaml
        build_output: deployment-post-ceph.yaml

  sriov:
    stages:
      - path: examples/va/nfv/sriov/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/nfv/sriov
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=600s
        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/va/nfv/sriov/edpm/nodeset
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=60m
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: nodeset.yaml

      - path: examples/va/nfv/sriov/edpm/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=60m
        values:
          - name: edpm-deployment-values
            src_file: values.yaml
        build_output: deployment.yaml

  ovs-dpdk:
    stages:
      - path: examples/va/nfv/ovs-dpdk/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/nfv/ovs-dpdk
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=600s
        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/va/nfv/ovs-dpdk/edpm/nodeset
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=60m
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: nodeset.yaml

      - path: examples/va/nfv/ovs-dpdk/edpm/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=60m
        values:
          - name: edpm-deployment-values
            src_file: values.yaml
        build_output: deployment.yaml

  ovs-dpdk-sriov:
    stages:
      - path: examples/va/nfv/ovs-dpdk-sriov/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/nfv/ovs-dpdk-sriov
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=1200s
        values:
          - name: network-values
            src_file: nncp/values.yaml
          - name: service-values
            src_file: service-values.yaml
        build_output: control-plane.yaml

      - path: examples/va/nfv/ovs-dpdk-sriov/edpm/nodeset
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=60m
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: nodeset.yaml

      - path: examples/va/nfv/ovs-dpdk-sriov/edpm/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=60m
        values:
          - name: edpm-deployment-values
            src_file: values.yaml
        build_output: deployment.yaml

  nfv-ovs-dpdk-sriov-hci:
    stages:
      - path: examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/nncp
        wait_conditions:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=5m
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane
        wait_conditions:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=60m
        values:
          - name: service-values
            src_file: service-values.yaml
          - name: network-values
            src_file: nncp/values.yaml
        build_output: ../control-plane.yaml

      - path: examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=60m
        values:
          - name: edpm-nodeset-values
            src_file: values.yaml
        build_output: nodeset-pre-ceph.yaml

      - path: examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=60m
        values:
          - name: edpm-deployment-values
            src_file: values.yaml
        build_output: deployment-pre-ceph.yaml
        post_stage_run:
          - name: Deploy Ceph
            type: playbook
            source: "../../playbooks/ceph.yml"
            inventory: "${HOME}/ci-framework-data/artifacts/zuul_inventory.yml"

      - path: examples/dt/nfv/nfv-ovs-dpdk-sriov-hci
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=SetupReady
            --timeout=60m
        values:
          - name: service-values
            src_file: service-values.yaml
          - name: edpm-nodeset-values-post-ceph
            src_file: values.yaml
        build_output: nodeset-post-ceph.yaml

      - path: examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/deployment
        wait_conditions:
          - >-
            oc -n openstack wait
            osdpns openstack-edpm --for condition=Ready
            --timeout=60m
        values:
          - name: edpm-deployment-values-post-ceph
            src_file: values.yaml
        build_output: deployment-post-ceph.yaml
