---
vas:
  hci:
    stages:
      - path: examples/va/hci/control-plane/nncp
        validations:
          - >-
            oc -n openstack wait nncp
            -l osp/nncm-config-type=standard
            --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
            --timeout=60s
        values:
          - name: network-values
            src_file: values.yaml
        build_output: nncp.yaml

      - path: examples/va/hci/control-plane
        validations:
          - >-
            oc -n openstack wait osctlplane controlplane --for condition=Ready
            --timeout=600s
        values:
          - name: network-values
        build_output: ../control-plane.yaml

      - path: examples/va/hci/edpm-pre-ceph
        validations:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment-pre-ceph --for condition=Ready
            --timeout=1200s
        values:
          - name: edpm-values
            src_file: values.yaml
        build_output: dataplane-pre-ceph.yaml
        post_stage_run:
          - name: Deploy Ceph
            type: playbook
            source: "../../playbooks/ceph.yml"
            inventory: "${HOME}/ci-framework-data/artifacts/zuul_inventory.yml"

      - path: examples/va/hci
        validations:
          - >-
            oc -n openstack wait
            osdpd edpm-deployment-post-ceph --for condition=Ready
            --timeout=1200s
        values:
          - name: service-values
            src_file: service-values.yaml
          - name: edpm-values-post-ceph
            src_file: values.yaml
        build_output: dataplane-post-ceph.yaml
