---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../va/nfv/ovs-dpdk-sriov/
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/ovs-dpdk-sriov?ref=main
  ## It's possible to replace ../../../../va/nfv/ovs-dpdk-sriov/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - nncp/values.yaml
  - service-values.yaml

replacements:
  # disable OCP workers as gateway nodes
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.ovn.ovnController.external-ids
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.ovn.template.ovnController.external-ids
        options:
          create: true
