---
# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # nodes
  node_0:
    name: master-0
    node_name: master-0
    internalapi_ip: "2620:cf:cf:bbbb::10"
    tenant_ip: "2620:cf:cf:eeee::10"
    ctlplane_ip: "2620:cf:cf:aaaa::10"
    storage_ip: "2620:cf:cf:cccc::10"
    ironic_ip: "2620:cf:cf:ffff::10"
    bgp_ip:
      - "2620:cf::100:64:0:10"
      - "2620:cf::100:65:0:10"
    bgp_peers:
      - "2620:cf::100:64:0:9"
      - "2620:cf::100:65:0:9"
    loopback_ip: 172.30.0.3
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:0:3
  node_1:
    name: master-1
    node_name: master-1
    internalapi_ip: "2620:cf:cf:bbbb::11"
    tenant_ip: "2620:cf:cf:eeee::11"
    ctlplane_ip: "2620:cf:cf:aaaa::11"
    storage_ip: "2620:cf:cf:cccc::11"
    ironic_ip: "2620:cf:cf:ffff::11"
    bgp_ip:
      - "2620:cf::100:64:1:10"
      - "2620:cf::100:65:1:10"
    bgp_peers:
      - "2620:cf::100:64:1:9"
      - "2620:cf::100:65:1:9"
    loopback_ip: 172.30.1.3
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:1:3
  node_2:
    name: master-2
    node_name: master-2
    internalapi_ip: "2620:cf:cf:bbbb::12"
    tenant_ip: "2620:cf:cf:eeee::12"
    ctlplane_ip: "2620:cf:cf:aaaa::12"
    storage_ip: "2620:cf:cf:cccc::12"
    ironic_ip: "2620:cf:cf:ffff::12"
    bgp_ip:
      - "2620:cf::100:64:2:10"
      - "2620:cf::100:65:2:10"
    bgp_peers:
      - "2620:cf::100:64:2:9"
      - "2620:cf::100:65:2:9"
    loopback_ip: 172.30.2.3
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:2:3
  node_3:
    name: worker-0
    node_name: worker-0
    internalapi_ip: "2620:cf:cf:bbbb::13"
    tenant_ip: "2620:cf:cf:eeee::13"
    ctlplane_ip: "2620:cf:cf:aaaa::13"
    storage_ip: "2620:cf:cf:cccc::13"
    ironic_ip: "2620:cf:cf:ffff::13"
    bgp_ip:
      - "2620:cf::100:64:0:14"
      - "2620:cf::100:65:0:14"
    bgp_peers:
      - "2620:cf::100:64:0:13"
      - "2620:cf::100:65:0:13"
    loopback_ip: 172.30.0.4
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:0:4
  node_4:
    name: worker-1
    node_name: worker-1
    internalapi_ip: "2620:cf:cf:bbbb::14"
    tenant_ip: "2620:cf:cf:eeee::14"
    ctlplane_ip: "2620:cf:cf:aaaa::14"
    storage_ip: "2620:cf:cf:cccc::14"
    ironic_ip: "2620:cf:cf:ffff::14"
    bgp_ip:
      - "2620:cf::100:64:1:14"
      - "2620:cf::100:65:1:14"
    bgp_peers:
      - "2620:cf::100:64:1:13"
      - "2620:cf::100:65:1:13"
    loopback_ip: 172.30.1.4
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:1:4
  node_5:
    name: worker-2
    node_name: worker-2
    internalapi_ip: "2620:cf:cf:bbbb::15"
    tenant_ip: "2620:cf:cf:eeee::15"
    ctlplane_ip: "2620:cf:cf:aaaa::15"
    storage_ip: "2620:cf:cf:cccc::15"
    ironic_ip: "2620:cf:cf:ffff::15"
    bgp_ip:
      - "2620:cf::100:64:2:14"
      - "2620:cf::100:65:2:14"
    bgp_peers:
      - "2620:cf::100:64:2:13"
      - "2620:cf::100:65:2:13"
    loopback_ip: 172.30.2.4
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:2:4
  node_6:
    name: worker-3
    node_name: worker-3
    internalapi_ip: "2620:cf:cf:bbbb::16"
    tenant_ip: "2620:cf:cf:eeee::16"
    ctlplane_ip: "2620:cf:cf:aaaa::16"
    storage_ip: "2620:cf:cf:cccc::16"
    ironic_ip: "2620:cf:cf:ffff::16"
    bgp_ip:
      - "2620:cf::100:64:10:2"
    bgp_peers:
      - "2620:cf::100:64:10:1"
    loopback_ip: 172.30.10.2
    loopback_ipv6: f00d:f00d:f00d:f00d:172:30:10:2
    base_if: enp7s0
    routes:  # TODO-edu
      config:
        - destination: 192.168.133.0/24
          next-hop-address: 100.64.6.9
          next-hop-interface: enp8s0

  # networks
  ctlplane:
    dnsDomain: ctlplane.example.com
    subnets:
      - allocationRanges:
          - end: "2620:cf:cf:aaaa::120"
            start: "2620:cf:cf:aaaa::100"
          - end: "2620:cf:cf:aaaa::200"
            start: "2620:cf:cf:aaaa::150"
        cidr: "2620:cf:cf:aaaa::0/64"
        gateway: "2620:cf:cf:aaaa::1"
        name: subnet1
    prefix-length: 64
    iface: enp7s0
    mtu: 9000
    lb_addresses:
      - "2620:cf:cf:aaaa::80-2620:cf:cf:aaaa::90"
    endpoint_annotations:
      metallb.universe.tf/address-pool: ctlplane
      metallb.universe.tf/allow-shared-ip: ctlplane
      metallb.universe.tf/loadBalancerIPs: "2620:cf:cf:aaaa::80"
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "ctlplane",
        "type": "macvlan",
        "master": "ospbr",
        "ipam": {
          "type": "whereabouts",
          "range": "2620:cf:cf:aaaa::0/64",
          "range_start": "2620:cf:cf:aaaa::30",
          "range_end": "2620:cf:cf:aaaa::70"
        }
      }
  internalapi:
    dnsDomain: internalapi.example.com
    subnets:
      - allocationRanges:
          - end: "2620:cf:cf:bbbb::250"
            start: "2620:cf:cf:bbbb::100"
        cidr: "2620:cf:cf:bbbb::0/64"
        name: subnet1
        vlan: 20
    mtu: 1500
    prefix-length: 64
    iface: internalapi
    vlan: 20
    base_iface: enp7s0
    lb_addresses:
      - "2620:cf:cf:bbbb::80-2620:cf:cf:bbbb::90"
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/allow-shared-ip: internalapi
      metallb.universe.tf/loadBalancerIPs: "2620:cf:cf:bbbb::80"
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "internalapi",
        "type": "macvlan",
        "master": "internalapi",
        "ipam": {
          "type": "whereabouts",
          "range": "2620:cf:cf:bbbb::0/64",
          "range_start": "2620:cf:cf:bbbb::30",
          "range_end": "2620:cf:cf:bbbb::70"
        }
      }
  storage:
    dnsDomain: storage.example.com
    subnets:
      - allocationRanges:
          - end: "2620:cf:cf:cccc::250"
            start: "2620:cf:cf:cccc::100"
        cidr: "2620:cf:cf:cccc::0/64"
        name: subnet1
        vlan: 21
    mtu: 9000
    prefix-length: 64
    iface: storage
    vlan: 21
    base_iface: enp7s0
    lb_addresses:
      - "2620:cf:cf:cccc::80-2620:cf:cf:cccc::90"
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "storage",
        "type": "macvlan",
        "master": "storage",
        "ipam": {
          "type": "whereabouts",
          "range": "2620:cf:cf:cccc::0/64",
          "range_start": "2620:cf:cf:cccc::30",
          "range_end": "2620:cf:cf:cccc::70"
        }
      }
  tenant:
    dnsDomain: tenant.example.com
    subnets:
      - allocationRanges:
          - end: "2620:cf:cf:eeee::250"
            start: "2620:cf:cf:eeee::100"
        cidr: "2620:cf:cf:eeee::0/64"
        name: subnet1
        vlan: 22
    mtu: 1500
    prefix-length: 64
    iface: tenant
    vlan: 22
    base_iface: enp7s0
    lb_addresses:
      - "2620:cf:cf:eeee::80-2620:cf:cf:eeee::90"
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "tenant",
        "type": "macvlan",
        "master": "tenant",
        "ipam": {
          "type": "whereabouts",
          "range": "2620:cf:cf:eeee::0/64",
          "range_start": "2620:cf:cf:eeee::30",
          "range_end": "2620:cf:cf:eeee::70"
        }
      }
  octavia:  # TODO-edu - change to ipv6
    dnsDomain: octavia.openstack.lab
    mtu: 1500
    vlan: 23
    base_iface: enp7s0
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "octavia",
        "type": "bridge",
        "bridge": "octbr",
        "ipam": {
          "type": "whereabouts",
          "range": "172.23.0.0/24",
          "range_start": "172.23.0.30",
          "range_end": "172.23.0.70",
          "routes": [
            {
              "dst": "172.24.0.0/16",
              "gw": "172.23.0.150"
            }
          ]
        }
      }
  external:
    dnsDomain: external.example.com
    subnets:
      - allocationRanges:
          - end: "2620:cf:cf:cf::250"
            start: "2620:cf:cf:cf::100"
        cidr: "2620:cf:cf:cf::/64"
        gateway: "2620:cf:cf:cf::1"
        name: subnet1
    mtu: 1500
  ironic:
    bridgeName: ironic
    cidr: '2620:cf:cf:ffff::0/64'
    mtu: 1500
    prefix-length: 64
    iface: ironic
    base_iface: enp10s0
    gateway: '2620:cf:cf:ffff::1'
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "ironic",
        "type": "macvlan",
        "master": "ironic",
        "ipam": {
          "type": "whereabouts",
          "range": "2620:cf:cf:ffff::0/64",
          "range_start": "2620:cf:cf:ffff::30",
          "range_end": "2620:cf:cf:ffff::70"
        }
      }

  bgp:
    prefix-length: 30
    ifaces:
      - enp8s0
      - enp9s0
    asn: 64999
    peer_asn: 64999
    subnets:
      bgpnet0:
        - name: subnet0
          allocationRanges:
            - end: 100.64.0.6
              start: 100.64.0.1
          cidr: 100.64.0.0/29
          gateway: 100.64.0.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.64.0.1
        - name: subnet1
          allocationRanges:
            - end: 100.64.1.6
              start: 100.64.1.1
          cidr: 100.64.1.0/29
          gateway: 100.64.1.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.64.1.1
        - name: subnet2
          allocationRanges:
            - end: 100.64.2.6
              start: 100.64.2.1
          cidr: 100.64.2.0/29
          gateway: 100.64.2.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.64.2.1
      bgpnet1:
        - name: subnet0
          allocationRanges:
            - end: 100.65.0.6
              start: 100.65.0.1
          cidr: 100.65.0.0/29
          gateway: 100.65.0.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.65.0.1
        - name: subnet1
          allocationRanges:
            - end: 100.65.1.6
              start: 100.65.1.1
          cidr: 100.65.1.0/29
          gateway: 100.65.1.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.65.1.1
        - name: subnet2
          allocationRanges:
            - end: 100.65.2.6
              start: 100.65.2.1
          cidr: 100.65.2.0/29
          gateway: 100.65.2.1
          routes:
            - destination: 0.0.0.0/0
              nexthop: 100.65.2.1
      bgpmainnet:
        - name: subnet0
          cidr: 172.30.0.0/28
          allocationRanges:
            - end: 172.30.0.14
              start: 172.30.0.2
        - name: subnet1
          cidr: 172.30.1.0/28
          allocationRanges:
            - end: 172.30.1.14
              start: 172.30.1.2
        - name: subnet2
          cidr: 172.30.2.0/28
          allocationRanges:
            - end: 172.30.2.14
              start: 172.30.2.2
        - name: subnet10
          cidr: 172.30.10.0/28
          allocationRanges:
            - end: 172.30.10.14
              start: 172.30.10.2
      bgpmainnetv6:
        - name: subnet0
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0010/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:001e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0012
        - name: subnet1
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0020/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:002e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0022
        - name: subnet2
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0030/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:003e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0032
        - name: subnet3
          cidr: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0040/124
          allocationRanges:
            - end: f00d:f00d:f00d:f00d:f00d:f00d:f00d:004e
              start: f00d:f00d:f00d:f00d:f00d:f00d:f00d:0042
    bgpdefs:
      node0:
        bgpnet0:
          bgp_peer: 100.64.0.9
          bgp_ip: 100.64.0.10
        bgpnet1:
          bgp_peer: 100.65.0.9
          bgp_ip: 100.65.0.10
      node1:
        bgpnet0:
          bgp_peer: 100.64.1.9
          bgp_ip: 100.64.1.10
        bgpnet1:
          bgp_peer: 100.65.1.9
          bgp_ip: 100.65.1.10
      node2:
        bgpnet0:
          bgp_peer: 100.64.2.9
          bgp_ip: 100.64.2.10
        bgpnet1:
          bgp_peer: 100.65.2.9
          bgp_ip: 100.65.2.10
      node3:
        bgpnet0:
          bgp_peer: 100.64.0.13
          bgp_ip: 100.64.0.14
        bgpnet1:
          bgp_peer: 100.65.0.13
          bgp_ip: 100.65.0.14
      node4:
        bgpnet0:
          bgp_peer: 100.64.1.13
          bgp_ip: 100.64.1.14
        bgpnet1:
          bgp_peer: 100.65.1.13
          bgp_ip: 100.65.1.14
      node5:
        bgpnet0:
          bgp_peer: 100.64.2.13
          bgp_ip: 100.64.2.14
        bgpnet1:
          bgp_peer: 100.65.2.13
          bgp_ip: 100.65.2.14
      node6:
        bgpnet0:
          bgp_peer: 100.64.10.1
          bgp_ip: 100.64.10.2
        routes:
          config:
            - destination: 192.168.133.0/24
              next-hop-address: 100.64.10.1
              next-hop-interface: enp8s0
    net-attach-def:
      node6: |
        {
          "cniVersion": "0.3.1",
          "name": "bgpnet-worker-3",
          "type": "host-device",
          "device": "enp8s0",
          "ipam": {
            "type": "whereabouts",
            "range": "100.64.10.0/30",
            "range_start": "100.64.10.2",
            "range_end": "100.64.10.2",
            "routes": [{
              "dst": "192.168.133.0/24",
              "gw": "100.64.10.1"
            }]
          }
        }

  loopback:
    prefix-length: 32
    prefix-length-ipv6: 128
    iface: lo
  datacentre:
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "datacentre",
        "type": "bridge",
        "bridge": "ospbr",
        "ipam": {}
      }

  dns-resolver:
    config:
      server:
        - "2620:cf:cf:aaaa::1"
      search: []
    options:
      - key: server
        values:
          - "2620:cf:cf:aaaa::1"

  routes:
    config: []

  rabbitmq:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: "2620:cf:cf:bbbb::81"
  rabbitmq-cell1:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: "2620:cf:cf:bbbb::82"

  lbServiceType: LoadBalancer
  storageClass: local-storage
  bridgeName: ospbr
