---
# local-config: referenced, but not emitted by kustomize
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-nodeset-values-ceph
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  nodeset:
    services:
      - bootstrap
      - configure-network
      - validate-network
      - install-os
      - configure-os
      - ssh-known-hosts
      - run-os
      - reboot-os
      - install-certs
      - ceph-client
      - ovn
      - neutron-metadata
      - libvirt
      - nova-custom-ceph
      - telemetry
  nova:
    ceph:
      conf: CHANGEME_NOVA_CEPH_CONF
  extraMounts:
    - extraVolType: Ceph
      volumes:
        - name: ceph
          secret:
            secretName: ceph-conf-files
      mounts:
        - name: ceph
          mountPath: "/etc/ceph"
          readOnly: true
