---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../va/nvidia-mdev/edpm/nodeset
  # - https://github.com/openstack-k8s-operators/architecture/va/nvidia-mdev/edpm/nodeset?ref=main
  ## It's possible to replace ../../../../../va/nvidia-mdev/edpm/nodeset/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.root_password
    targets:
      - select:
          kind: Secret
          name: baremetalset-password-secret
        fieldPaths:
          - data.NodeRootPassword
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.preProvisioned
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-edpm
        fieldPaths:
          - spec.preProvisioned
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.baremetalSetTemplate
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
          name: openstack-edpm
        fieldPaths:
          - spec.baremetalSetTemplate
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova.compute.conf
    targets:
      - select:
          kind: ConfigMap
          name: cpu-pinning-nova
        fieldPaths:
          - data.25-cpu-pinning-nova\.conf
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova.pci.conf
    targets:
      - select:
          kind: ConfigMap
          name: sriov-nova
        fieldPaths:
          - data.03-sriov-nova\.conf
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova.mdev.nvidia_mdev_driver_url
    targets:
      - select:
          kind: ConfigMap
          name: nvidia-url
        fieldPaths:
          - data.nvidia_mdev_driver_url
        options:
          create: true
