---
apiVersion: v1
kind: ConfigMap

metadata:
  name: edpm-nodeset-post-driver-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  deployment:
    name: edpm-deployment-post-driver
  servicesOverride:
    - reboot-os
  ansibleExtraVars:
    edpm_reboot_strategy: force
