---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../va/vaf/amd/mi300x-vgpu
  # - https://github.com/openstack-k8s-operators/architecture/va/vaf/amd/mi300x-vgpu?ref=main
  ## It's possible to replace ../../../../../va/vaf/amd/mi300x-vgpu with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - nncp/values.yaml
  - service-values.yaml
