---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
      apiVersion: builtin
      kind: NamespaceTransformer
      metadata:
        name: _ignored_
        namespace: openstack
      setRoleBindingSubjects: none
      unsetOnly: true
      fieldSpecs:
        - path: metadata/name
          kind: Namespace
          create: true

components:
  - ../../../lib/networking/metallb
  - ../../../lib/networking/netconfig
  - ../../../lib/networking/nad

resources:
  - ocp-networks-octavia-netattach.yaml
  - ocp-networks-ospbr-218-netattach.yaml
  - ocp-networks-ospbr-100-netattach.yaml
  - ocp-networks-ospbr-101-netattach.yaml


patches:
  - target:
      kind: NetConfig
      name: netconfig
    patch: |-
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: ospbr-218
          subnets:
            - _replaced_
          mtu: 9000

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ospbr-218.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=ospbr-218].dnsDomain

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ospbr-218.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=ospbr-218].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ospbr-218.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=ospbr-218].subnets

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: octavia
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ospbr-218.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: ospbr-218
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ospbr-100.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: ospbr-100
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ospbr-101.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: ospbr-101
        fieldPaths:
          - spec.config
