---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  preserveJobs: false
  glance:
    customServiceConfig: |
      [DEFAULT]
      enabled_backends = default_backend:swift
      [glance_store]
      default_backend = default_backend
      [default_backend]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}
    default:
      replicas: 1

  swift:
    enabled: true

  octavia:
    enabled: false
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    octaviaAPI:
      networkAttachments:
        - internalapi
    octaviaHousekeeping:
      networkAttachments:
        - octavia
    octaviaHealthManager:
      networkAttachments:
        - octavia
    octaviaWorker:
      networkAttachments:
        - octavia

  ovn:
    ovnController:
      nicMappings:
        datacentre: ocpbr
        octavia: octbr
        ironic: ironic
      external-ids:
        enable-chassis-as-gateway: false
  neutron:
    customServiceConfig: |
      [DEFAULT]
      vlan_transparent = true
      debug = true
      [ovs]
      igmp_snooping_enable = true

  ironic:
    enabled: true
    rpcTransport: oslo
    ironicConductors:
      - customServiceConfig: |
          [pxe]
          kernel_append_params = console=ttyS0

          [neutron]
          cleaning_network = provisioning
          provisioning_network = provisioning
          rescuing_network = provisioning
          inspection_network = provisioning
    ironicInspector:
      customServiceConfig: |
        [capabilities]
        boot_mode = true

        [processing]
        update_pxe_enabled = false

  nova:
    cellTemplates:
      cell0:
        cellDatabaseInstance: openstack
        cellDatabaseAccount: nova-cell0
        cellMessageBusInstance: rabbitmq
        hasAPIAccess: true
      cell1:
        cellDatabaseInstance: openstack-cell1
        cellDatabaseAccount: nova-cell1
        cellMessageBusInstance: rabbitmq-cell1
        hasAPIAccess: true
        novaComputeTemplates:
          compute-ironic:
            computeDriver: ironic.IronicDriver
