---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  provisioningDHCPRange: null
  provisioningIP: null
  provisioningInterface: null
  provisioningMacAddresses: null
  provisioningNetwork: Disabled
  provisioningNetworkCIDR: null
  watchAllNamespaces: true
  virtualMediaViaExternalNetwork: true
