---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../va/nfv/ovs-dpdk-sriov/edpm/compute-nodeset
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/ovs-dpdk-sriov/edpm/compute-nodeset?ref=main
  ## It's possible to replace ../../../../../../va/nfv/ovs-dpdk-sriov/edpm/compute-nodeset/ with a git checkout URL
  ## as per: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: compute-nodes
