---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../dt/nova/nova02beta/edpm/deployment
  # - https://github.com/openstack-k8s-operators/architecture/dt/nova/nova02beta/edpm/deployment?ref=main
  ## It's possible to replace ../../../../../../dt/nova/nova02beta/edpm/deployment/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneDeployment
      name: edpm-deployment
    patch: |
      - op: add
        path: /spec/nodeSets/-
        value: openstack-edpm-2
