#
# CHANGEME:
#
# - Change "data.authorized_keys" as indicated below
# - Change "data.ssh-privatekey" as indicated below
# - Change "data.ssh-publickey" as indicated below
#

apiVersion: v1
data:
  # authorized_keys are the public keys that are allowed to SSH to the compute nodes.  It can be set like so:
  # KEYDATA=$(cat <pub key file> | base64 -w 0) yq -i '(.data["authorized_keys"])=("${KEYDATA}" | envsubst)' dataplanesshsecret.yaml
  authorized_keys: # CHANGEME
  # ssh-privatekey is the private key that can SSH to compute nodes.  It can be set like so:
  # KEYDATA=$(cat <private key file> | base64 -w 0) yq -i '(.data["ssh-privatekey"])=("${KEYDATA}" | envsubst)' dataplanesshsecret.yaml
  ssh-privatekey: # CHANGEME
  # ssh-publickey is the public key that can SSH to compute nodes. It can be set like so:
  # KEYDATA=$(cat <pub key file> | base64 -w 0) yq -i '(.data["ssh-publickey"])=("${KEYDATA}" | envsubst)' dataplanesshsecret.yaml
  ssh-publickey: # CHANGEME
kind: Secret
metadata:
  name: dataplane-ansible-ssh-private-key-secret
  namespace: openstack
type: Opaque
