---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../va/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset?ref=main
  ## It's possible to replace ../../../../../../va/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset with a git checkout URL
  ## as per: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml
