---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-provider-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  nova:
    compute:
      provider: |
        meta:
          schema_version: "1.0"
        providers:
          - identification:
              name: edpm-compute-0.ctlplane.example.com_pci_0000_04_00_0
            traits:
              additional:
                - CUSTOM_NVIDIA_229
          - identification:
              name: edpm-compute-0.ctlplane.example.com_pci_0000_82_00_0
            traits:
              additional:
                - CUSTOM_NVIDIA_228
          - identification:
              name: edpm-compute-1.ctlplane.example.com_pci_0000_04_00_0
            traits:
              additional:
                - CUSTOM_NVIDIA_229
          - identification:
              name: edpm-compute-1.ctlplane.example.com_pci_0000_82_00_0
            traits:
              additional:
                - CUSTOM_NVIDIA_228
