---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../lib/networking/metallb
  - ../../lib/networking/netconfig
  - ../../lib/networking/nad
  - ../../lib/control-plane

patches:
  #
  # The storagemgmt network template needed for CephHCI
  #
  - target:
      version: v1beta1
      kind: NetConfig
      name: netconfig
    patch: |-
      - op: add
        path: /spec/networks/-
        value:
          dnsDomain: _replaced_
          name: storagemgmt
          subnets:
            - _replaced_
          mtu: 1500

replacements:
  #
  # The storagemgmt network replacements
  #
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.dnsDomain
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].dnsDomain

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.galera.templates.openstack-cell2
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.galera.templates.openstack-cell2
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.rabbitmq-cell2.endpoint_annotations
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates.rabbitmq-cell2.override.service.metadata.annotations
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.rabbitmq.templates.rabbitmq-cell2.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates.rabbitmq-cell2.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.lbServiceType
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates.rabbitmq-cell2.override.service.spec.type
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.template.cellTemplates.cell2
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.cellTemplates.cell2
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.mtu
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storagemgmt.subnets
    targets:
      - select:
          kind: NetConfig
        fieldPaths:
          - spec.networks.[name=storagemgmt].subnets
