---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../../lib/dataplane/nodeset

resources:
  - bm_password.yaml
  - nova_ceph.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: compute-nodes

  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    path: extra_mounts.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-post-ceph
      fieldPath: data.nova.ceph.conf
    targets:
      - select:
          kind: ConfigMap
          name: ceph-nova
        fieldPaths:
          - data.03-ceph-nova\.conf
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nodeset.services
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.services
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.root_password
    targets:
      - select:
          kind: Secret
          name: baremetalset-password-secret
        fieldPaths:
          - data.NodeRootPassword
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.preProvisioned
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.preProvisioned
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.baremetalSetTemplate
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.baremetalSetTemplate
        options:
          create: true
