---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
      apiVersion: builtin
      kind: NamespaceTransformer
      metadata:
        name: _ignored_
        namespace: openstack
      setRoleBindingSubjects: none
      unsetOnly: true
      fieldSpecs:
        - path: metadata/name
          kind: Namespace
          create: true

components:
  - ../../../lib/networking/metallb
  - netconfig
  - ../../../lib/networking/nad

resources:
  - nad.yaml

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: octavia
        fieldPaths:
          - spec.config

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ironic.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: ironic
        fieldPaths:
          - spec.config
