---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../dt/uni05epsilon/edpm-post-ceph/nodeset2

resources:
  - edpm-pre-ceph/values.yaml
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: openstack-edpm
    patch: |-
      - op: replace
        path: /metadata/name
        value: openstack-edpm-2
  - target:
      kind: OpenStackDataPlaneService
      name: nova-custom
    patch: |-
      - op: replace
        path: /metadata/name
        value: nova-custom-cell2
      - op: replace
        path: /spec/label
        value: nova-custom-cell2
      - op: replace
        path: /spec/dataSources/1/secretRef/name
        value: nova-cell2-compute-config
