---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm
spec:
  nodeTemplate:
    extraMounts:
      - extraVolType: Ceph
        mounts:
          - mountPath: /etc/ceph
            name: ceph
            readOnly: true
        volumes:
          - name: ceph
            secret:
              secretName: ceph-conf-files
