# local-config: referenced, but not emitted by kustomize
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: olm-values
    annotations:
        config.kubernetes.io/local-config: 'true'
data:
    openstack-operator-channel: "alpha"
    openstack-operator-image: "quay.io/openstack-k8s-operators/openstack-operator-index:latest"
    openstack-operator-display-name: "CI Test"
    openstack-operator-installplanapproval: "Automatic"
    openstack-operator-publisher: "Testing Team"
    openstack-operator-catalog-source: "openstack-operator-index"
    openstack-operator-subscription-namespace: "openstack-operators"
    openstack-operator-version: "latest"
