---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openstack

components:
  - ../../../../../../../va/vaf/nvidia/rtx-pro-6000-gpu-passthrough/edpm/baremetalhosts

resources:
  - values.yaml

secretGenerator:
  - name: bmc-secret
    behavior: create
    envs:
      - bmc-secret.env
    options:
      disableNameSuffixHash: true
