---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  tls:
    caBundleSecretName: custom-ca-certs
  barbican:
    barbicanKeystoneListener:
      customServiceConfig: |
        [keystone_notifications]
        pool_name = barbican-listener-regionOne
  cinderBackup:
    customServiceConfig: |
      [DEFAULT]
      backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver
      backup_swift_auth = single_user
      backup_swift_user = service:cinder
      backup_swift_key = {{ .ServicePassword }}
      backup_swift_tenant = service
      backup_swift_auth_version = 3
      backup_swift_project_domain = Default
      backup_swift_user_domain = Default
    replicas: 1
  cinderVolumes:
    lvm-iscsi:
      replicas: 1
      nodeSelector:
        openstack.org/cinder-lvm: ""
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = lvm
        [lvm]
        volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
        volume_group = cinder-volumes
        target_protocol = iscsi
        target_helper = lioadm
        volume_backend_name = lvm_iscsi
        target_ip_address = 172.18.0.10
  swift:
    enabled: true
