---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../dt/uni05epsilon/edpm-pre-ceph/nodeset

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: openstack-edpm
    patch: |-
      - op: replace
        path: /metadata/name
        value: openstack-edpm-2
