---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - lvms-cluster.yaml
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: lvms-values
      fieldPath: data.paths
    targets:
      - select:
          kind: LVMCluster
        fieldPaths:
          - spec.storage.deviceClasses.[name=vg1].deviceSelector.paths
