---
apiVersion: v1
kind: ConfigMap

metadata:
  name: edpm-nodeset-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  ssh_keys:
    authorized: _replaced_
    private: _replaced_
    public: _replaced_

  nova:
    migration:
      ssh_keys:
        private: _replaced_
        public: _replaced_

    ceph:
      conf: _replaced_

  root_password: cmVkaGF0Cg==
  preProvisioned: false

  baremetalSetTemplate:
    ctlplaneInterface: ens1f1
    provisioningInterface: ens1f0

    cloudUserName: cloud-admin
    bmhLabelSelector:
      app: openstack

    passwordSecret:
      name: baremetalset-password-secret
      namespace: openstack

  nodeset:
    ansible:
      ansibleUser: zuul
      ansiblePort: 22
      ansibleVars:
        service_net_map:
          nova_api_network: internalapi
          nova_libvirt_network: internalapi
        timesync_ntp_servers:
          - hostname: clock.redhat.com
        edpm_network_config_hide_sensitive_logs: false
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
            - type: ovs_bridge
              name: {{ neutron_physical_bridge_name }}
              mtu: {{ external_mtu }}
              use_dhcp: false
              members:
                - type: interface
                  name: nic1
                  mtu: {{ external_mtu }}
                  primary: true
            - type: ovs_bridge
              name: br-osp
              mtu: {{ min_viable_mtu }}
              use_dhcp: false
              dns_servers: {{ ctlplane_dns_nameservers }}
              domain: {{ dns_search_domains }}
              addresses:
                - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
              routes: {{ ctlplane_host_routes }}
              members:
                - type: interface
                  name: nic2
                  mtu: {{ min_viable_mtu }}
                  primary: true
          {% for network in nodeset_networks %}
          {% if network != 'external' %}
                - type: vlan
                  mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                  vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
                  addresses:
                    - ip_netmask: >-
                        {{
                          lookup('vars', networks_lower[network] ~ '_ip')
                        }}/{{
                          lookup('vars', networks_lower[network] ~ '_cidr')
                        }}
                  routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
          {% endif %}
          {% endfor %}
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth0

        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false

        edpm_selinux_mode: enforcing
        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges:
          - 192.168.122.0/24

        enable_debug: false
        gather_facts: false

    networks:
      - defaultRoute: true
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
      - name: external
        subnetName: external

    nodes:
      edpm-compute-0:
        ansible:
          ansibleHost: 192.168.122.100
        hostName: edpm-compute-0
        networks:
          - defaultRoute: true
            fixedIP: 192.168.122.100
            name: ctlplane
            subnetName: subnet1
          - name: internalapi
            subnetName: subnet1
          - name: storage
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1
          - name: external
            subnetName: subnet1

    services:
      - bootstrap
      - configure-network
      - validate-network
      - install-os
      - configure-os
      - ssh-known-hosts
      - run-os
      - reboot-os
      - install-certs
      - ceph-client
      - ovn
      - neutron-metadata
      - libvirt
      - nova-custom-ceph
      - telemetry
