---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-igmp
data:
  25-igmp.conf: _replaced_
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-ovn-igmp
spec:
  label: neutron-ovn-igmp
  edpmServiceType: neutron-ovn
  configMaps:
    - neutron-igmp
  caCerts: combined-ca-bundle
  playbook: osp.edpm.neutron_ovn
  secrets:
    - neutron-ovn-agent-neutron-config
  tlsCert:
    contents:
      - dnsnames
      - ips
    issuer: osp-rootca-issuer-ovn
    keyUsages:
      - digital signature
      - key encipherment
      - client auth
    networks:
      - ctlplane
