---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-nodeset-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  ssh_keys:
    authorized: _replaced_
    private: _replaced_
    public: _replaced_

  ceph:
    conf: CHANGEME_CEPH_CONF
    keyring: CHANGEME_CEPH_KEYRING

  nova:
    ceph:
      conf: CHANGEME_NOVA_CEPH_CONF

    migration:
      ssh_keys:
        private: _replaced_
        public: _replaced_

  nodeset:
    ansible:
      ansibleUser: cloud-admin
      ansiblePort: 22
      ansibleVars:
        timesync_ntp_servers:
          - hostname: clock.redhat.com

        edpm_iscsid_image: '{{ registry_url }}/openstack-iscsid:{{ image_tag }}'
        edpm_logrotate_crond_image: '{{ registry_url }}/openstack-cron:{{ image_tag }}'
        edpm_network_config_hide_sensitive_logs: false

        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in nodeset_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
            - type: ovs_bridge
              name: {{ neutron_physical_bridge_name }}
              mtu: {{ min_viable_mtu }}
              use_dhcp: false
              dns_servers: {{ ctlplane_dns_nameservers | list }}
              domain: {{ dns_search_domains }}
              addresses:
                - ip_netmask: '{{ ctlplane_ip }}/{{ ctlplane_cidr }}'
              routes: {{ ctlplane_host_routes }}
              members:
                - type: interface
                  name: nic2
                  mtu: {{ min_viable_mtu }}
                  primary: true
          {% for network in nodeset_networks %}
                - type: vlan
                  mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                  vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
                  addresses:
                    - ip_netmask: >-
                        {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
                  routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
          {% endfor %}

        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false

        edpm_ovn_encap_tos: "inherit"
        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges:
          - '2620:cf:cf:aaaa::0/64'

        gather_facts: false

        image_tag: current-podified
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth0
        registry_url: quay.io/podified-antelope-centos9


        storage_mtu: 9000
        storage_mgmt_mtu: 9000
        storage_mgmt_vlan_id: 23
        storage_mgmt_cidr: "24"
        storage_mgmt_host_routes: []

    networks:
      - defaultRoute: true
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
      - name: storagemgmt
        subnetName: subnet1

    nodes:
      edpm-compute-0:
        ansible:
          ansibleHost: '2620:cf:cf:aaaa::100'
        hostName: edpm-compute-0
        networks:
          - defaultRoute: true
            fixedIP: '2620:cf:cf:aaaa::100'
            name: ctlplane
            subnetName: subnet1
          - name: internalapi
            subnetName: subnet1
          - name: storage
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1
      edpm-compute-1:
        ansible:
          ansibleHost: '2620:cf:cf:aaaa::101'
        hostName: edpm-compute-1
        networks:
          - defaultRoute: true
            fixedIP: '2620:cf:cf:aaaa::101'
            name: ctlplane
            subnetName: subnet1
          - name: internalapi
            subnetName: subnet1
          - name: storage
            subnetName: subnet1
          - name: tenant
            subnetName: subnet1

    services:
      - bootstrap
      - configure-network
      - validate-network
      - install-os
      - configure-os
      - ssh-known-hosts
      - run-os
      - reboot-os
      - install-certs
      - ceph-client
      - ovn
      - neutron-metadata
      - libvirt
      - nova-custom-ceph
