# yamllint disable rule:line-length
# local-config: referenced, but not emitted by kustomize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-deployment-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  deployment:
    name: edpm-deployment-pre-ceph
  servicesOverride:
    - bootstrap
    - download-cache
    - reboot-os
    - configure-ovs-dpdk
    - configure-network
    - install-os
    - validate-network
    - ceph-hci-pre
    - configure-os
    - ssh-known-hosts
    - run-os
