---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

components:
  - ../../../../lib/control-plane
  - ../../../../lib/dataplane/nodeset

resources:
  - ceph_secret.yaml
  - nova_ceph.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    path: extra_mounts.yaml

replacements:
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.ceph
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.ceph
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.glanceAPIs.default.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.manila.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.manila.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.extraMounts
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.extraMounts
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.neutron.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.neutron.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.ceph.keyring
    targets:
      - select:
          kind: Secret
          name: ceph-conf-files
        fieldPaths:
          - data.ceph\.client\.openstack\.keyring
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.ceph.conf
    targets:
      - select:
          kind: Secret
          name: ceph-conf-files
        fieldPaths:
          - data.ceph\.conf
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nova.ceph.conf
    targets:
      - select:
          kind: ConfigMap
          name: ceph-nova
        fieldPaths:
          - data.03-ceph-nova\.conf
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values
      fieldPath: data.nodeset.services
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.services
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.neutron.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.neutron.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.designate-redis.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.redis.templates.designate-redis.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.designate-redis.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.redis.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.designate.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.designate.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.designate.bind9Services
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.designate.template.designateBackendbind9.override
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.designate.nsRecords
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.designate.template.nsRecords
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.enabled
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.amphoraImageContainerImage
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.amphoraImageContainerImage
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.apacheContainerImage
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.apacheContainerImage
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaAPI.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaAPI.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaHousekeeping.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaHousekeeping.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaHealthManager.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaHealthManager.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.octavia.octaviaWorker.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.octavia.template.octaviaWorker.networkAttachments
        options:
          create: true
