---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../va/nfv/ovs-dpdk-sriov/edpm/deployment

patches:
  - target:
      kind: OpenStackDataPlaneDeployment
      name: edpm-deployment
    patch: |
      - op: add
        path: /spec/nodeSets/-
        value: openstack-edpm-2
