apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: _ignored_
  namespace: openstack
setRoleBindingSubjects: none
unsetOnly: true
fieldSpecs:
- path: metadata/name
  kind: Namespace
  create: true
