apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
# Set namespace to OpenStack on all namespaced objects without a namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openstack
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true

components:
- ../../../../lib/dataplane

resources:
- nova_sriov.yaml

replacements:
# Nova compute CPU pinning customization
- source:
    kind: ConfigMap
    name: edpm-values
    fieldPath: data.nova.compute.conf
  targets:
  - select:
      kind: ConfigMap
      name: cpu-pinning-nova
    fieldPaths:
    - data.25-cpu-pinning-nova\.conf
    options:
      create: true
# Nova compute PCI passthrough customization
- source:
    kind: ConfigMap
    name: edpm-values
    fieldPath: data.nova.pci.conf
  targets:
  - select:
      kind: ConfigMap
      name: sriov-nova
    fieldPaths:
    - data.03-sriov-nova\.conf
    options:
      create: true
