---
# Define the "cinder-volume-nfs-secrets" Secret that contains sensitive
# information pertaining to the [nfs] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-nfs-secrets
type: Opaque
stringData:
  cinder-volume-nfs-secrets: _replaced_
