---
# Define the "s3glance" Secret that contains sensitive
# information pertaining to the [s3] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: glance
  name: s3glance
type: Opaque
stringData:
  s3glance.conf: _replaced_
