---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - l2advertisement.yaml
  - pools.yaml

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designate.lb_addresses
    targets:
      - select:
          kind: IPAddressPool
          name: designate
        fieldPaths:
          - spec.addresses

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designateext.lb_addresses
    targets:
      - select:
          kind: IPAddressPool
          name: designateext
        fieldPaths:
          - spec.addresses

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designate.iface
    targets:
      - select:
          group: metallb.io
          kind: L2Advertisement
          name: designate
        fieldPaths:
          - spec.interfaces.0

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.designateext.iface
    targets:
      - select:
          group: metallb.io
          kind: L2Advertisement
          name: designateext
        fieldPaths:
          - spec.interfaces.0
