---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: designate
  labels:
    osp/lb-addresses-type: standard
spec:
  addresses:
    - __replaced__
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: designateext
  labels:
    osp/lb-addresses-type: standard
spec:
  addresses:
    - __replaced__
