---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../va/nfv/ovs-dpdk-sriov/edpm/deployment
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/ovs-dpdk-sriov/edpm/deployment?ref=main
  ## It's possible to replace ../../../../../../va/nfv/ovs-dpdk-sriov/edpm/deployment/ with a git checkout URL
  ## as per: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-deployment-values
      fieldPath: data.nodeSets
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.nodeSets
