---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

resources:
  - nova_provider.yaml

replacements:
  # Nova provider yaml configuration
  - source:
      kind: ConfigMap
      name: edpm-provider-values
      fieldPath: data.nova.compute.provider
    targets:
      - select:
          kind: ConfigMap
          name: compute-provider
        fieldPaths:
          - data.provider\.yaml
        options:
          create: true
