---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../../lib/control-plane
  - ../../../../lib/dataplane/nodeset

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: .*
    path: resources/ceph-extra-mounts.yaml

resources:
  - resources/ceph-secret.yaml
  - resources/cinder-volume-nfs-secrets.yaml
  - resources/cinder-volume-ontap-secrets.yaml
  - resources/nova-custom-config.yaml
  - resources/nova-custom-service.yaml

replacements:
  #
  # Ceph
  #
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-post-ceph
      fieldPath: data.ceph.conf
    targets:
      - select:
          kind: Secret
          name: ceph-conf-files
        fieldPaths:
          - data.ceph\.conf
        options:
          create: true

  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-post-ceph
      fieldPath: data.ceph.keyring
    targets:
      - select:
          kind: Secret
          name: ceph-conf-files
        fieldPaths:
          - data.ceph\.client\.openstack\.keyring
        options:
          create: true

  #
  # Cinder
  #
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderBackup.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderBackup.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.ceph.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.ceph.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.ceph.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.ceph.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.nfs.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.nfs.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.nfs.customServiceConfigSecrets
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.nfs.customServiceConfigSecrets
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.nfs.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.nfs.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinder-volume-nfs-secrets
    targets:
      - select:
          kind: Secret
          name: cinder-volume-nfs-secrets
        fieldPaths:
          - stringData.cinder-volume-nfs-secrets
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.ontap-iscsi.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.ontap-iscsi.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.ontap-iscsi.customServiceConfigSecrets
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.ontap-iscsi.customServiceConfigSecrets
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinderVolumes.ontap-iscsi.networkAttachments
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.cinder.template.cinderVolumes.ontap-iscsi.networkAttachments
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.cinder-volume-ontap-secrets
    targets:
      - select:
          kind: Secret
          name: cinder-volume-ontap-secrets
        fieldPaths:
          - stringData.cinder-volume-ontap-secrets
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.galera.templates.openstack-cell2
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.galera.templates.openstack-cell2
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.rabbitmq-cell2.endpoint_annotations
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates.rabbitmq-cell2.override.service.metadata.annotations
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.rabbitmq.templates.rabbitmq-cell2.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates.rabbitmq-cell2.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.lbServiceType
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.rabbitmq.templates.rabbitmq-cell2.override.service.spec.type
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova.template.cellTemplates.cell2
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.nova.template.cellTemplates.cell2
        options:
          create: true

  #
  # Dataplane services override
  #
  # (overrides /lib/dataplane which is using edpm-nodeset-values ConfigMap)
  #
  - source:
      kind: ConfigMap
      name: edpm-nodeset-values-post-ceph
      fieldPath: data.nodeset.services
    targets:
      - select:
          kind: OpenStackDataPlaneNodeSet
        fieldPaths:
          - spec.services
        options:
          create: true

  #
  # Extra mounts for Cinder and Glance
  #
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.extraMounts
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.extraMounts
        options:
          create: true

  #
  # Glance
  #
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.customServiceConfig
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.databaseInstance
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.databaseInstance
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.glanceAPIs.default.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.replicas
        options:
          create: true

  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.glanceAPIs.default.type
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.type
        options:
          create: true

  #
  # Nova
  #
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.nova-extra-config
    targets:
      - select:
          kind: ConfigMap
          name: nova-custom-config
        fieldPaths:
          - data.55-nova-extra\.conf
        options:
          create: true

  #
  # Swift
  #
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.swift.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.swift.enabled
        options:
          create: true
