---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edpm-deployment-values-post-ceph-2
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  deployment:
    name: edpm-deployment-post-ceph-2
    spec:
      nodeSets:
        - openstack-edpm-2
  servicesOverride:
    - install-certs
    - ceph-client
    - ovn
    - neutron-metadata
    - libvirt
    - nova-custom-cell2
