---
apiVersion: v1
kind: Secret
metadata:
  name: edpm-compute-0-preprovision-network-data
  namespace: openstack
type: Opaque
stringData: {}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  labels: {}
  name: edpm-compute-0
  namespace: openstack
  annotations:
    inspect.metal3.io: ""
spec:
  architecture: x86_64
  automatedCleaningMode: metadata
  bmc:
    address: _replaced_
    credentialsName: _replaced_
  bootMACAddress: _replaced_
  bootMode: UEFI
  rootDeviceHints: {}
  online: true
