---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # --- Fields required by lib/control-plane ---
  tls:
    caBundleSecretName: custom-ca-certs

  # --- SKMO-specific overrides ---
  barbican:
    barbicanKeystoneListener:
      customServiceConfig: |
        [keystone_notifications]
        pool_name = barbican-listener-regionTwo
  horizon:
    enabled: false
  keystone:
    externalKeystoneAPI: true
  glance:
    customServiceConfig: |
      [DEFAULT]
      enabled_backends = default_backend:swift
      [glance_store]
      default_backend = default_backend
      [default_backend]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}
      swift_store_region = regionTwo
  cinderBackup:
    customServiceConfig: |
      [DEFAULT]
      backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver
      backup_swift_auth = single_user
      backup_swift_user = service:cinder
      backup_swift_key = {{ .ServicePassword }}
      backup_swift_tenant = service
      backup_swift_auth_version = 3
      backup_swift_project_domain = Default
      backup_swift_user_domain = Default
    replicas: 1
  cinderVolumes:
    lvm-iscsi:
      replicas: 1
      nodeSelector:
        openstack.org/cinder-lvm: ""
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = lvm
        [lvm]
        volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
        volume_group = cinder-volumes
        target_protocol = iscsi
        target_helper = lioadm
        volume_backend_name = lvm_iscsi
        target_ip_address = 172.18.10.10
