---
name: file-consistency
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - stable
    paths:
      - "**.yaml"
      - "**.yml"
      - test-kustomizations.sh

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4

      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: '3.14'

      - name: Install yaml-lint
        run: pip install yamllint

      - name: Run yaml-lint
        run: yamllint -c .yamllint.yml -s .

  test-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4

      - name: Get Kustomize
        uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f  # v2

      - name: Run test-kustomization script
        run: |
          kustomize version
          ./test-kustomizations.sh examples/

  test-zuul:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4

      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: '3.14'

      - name: Install yaml
        run: pip install pyyaml

      - name: Run create-zuul-jobs
        run: |
          sha256sum zuul.d/* > checksum;
          ./create-zuul-jobs.py;
          sha256sum -c checksum || (git diff && exit 1) && exit 0;
