---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

resources:
  - nncp.yaml

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      labelSelector: "osp/nncm-config-type=standard"
    path: node_template.yaml

replacements:
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.mtu
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.mtu
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.mtu
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[type=ethernet].name
          - spec.desiredState.interfaces.[name=ospbr].bridge.port.0.name

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.mtu
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[type=ethernet].mtu
          - spec.desiredState.interfaces.[name=ospbr].mtu

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.internalapi_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.tenant_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.ctlplane_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=ospbr].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.storage_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.internalapi_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.tenant_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.ctlplane_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=ospbr].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.storage_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.internalapi_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.tenant_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.ctlplane_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=ospbr].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.storage_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.ip

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=ospbr].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=ospbr].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=ospbr].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.prefix-length

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_0.name
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-0
        fieldPaths:
          - metadata.name
          - spec.nodeSelector.[kubernetes.io/hostname]

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_1.name
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-1
        fieldPaths:
          - metadata.name
          - spec.nodeSelector.[kubernetes.io/hostname]

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_2.name
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-2
        fieldPaths:
          - metadata.name
          - spec.nodeSelector.[kubernetes.io/hostname]
