---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy

metadata:
  name: _ignored_

spec:
  nodeSelector:
    kubernetes.io/hostname: _replaced_
    node-role.kubernetes.io/worker: ""

  desiredState:
    interfaces:
      - description: internalapi vlan interface
        ipv4:
          address:
            - ip: _replaced_
              prefix-length: _replaced_
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: internalapi
        state: up
        type: vlan
        vlan:
          base-iface: _replaced_
          id: _replaced_
        mtu: 1500

      - description: storage vlan interface
        ipv4:
          address:
            - ip: _replaced_
              prefix-length: _replaced_
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: storage
        state: up
        type: vlan
        vlan:
          base-iface: _replaced_
          id: _replaced_
        mtu: 1500

      - description: tenant vlan interface
        ipv4:
          address:
            - ip: _replaced_
              prefix-length: _replaced_
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: tenant
        state: up
        type: vlan
        vlan:
          base-iface: _replaced_
          id: _replaced_
        mtu: 1500

      - description: ctlplane interface
        name: _replaced_
        state: up
        type: ethernet
        mtu: 1500

      - description: linux-bridge over ctlplane interface
        ipv4:
          address:
            - ip: _replaced_
              prefix-length: _replaced_
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: ospbr
        state: up
        type: linux-bridge
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: _replaced_
              vlan: {}
        mtu: 1500

      - description: Octavia vlan interface
        name: octavia
        state: up
        type: vlan
        vlan:
          base-iface: _replaced_
          id: _replaced_

      - description: linux-bridge for Octavia
        mtu: 1500
        name: br-octavia
        type: linux-bridge
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: octavia
